Fixes closing mobile menu.
MatvienkoDO/grid-dynamics-internship-project pull request #139
Opened 2019-11-11 20:03 UTC by linkouth

Added click event listener on menu__item

2019-11-12 06:32 UTC, usersadvocate approved these changes

2019-11-12 08:08 UTC, MatvienkoDO requested changes

2019-11-12 08:08 UTC, MatvienkoDO commented on frontend/src/app/core/header/header.component.ts
> +    private elRef:ElementRef
space after colon

2019-11-12 08:08 UTC, MatvienkoDO commented on frontend/src/app/core/header/header.component.ts
>  import { NotificationService } from '../../shared/services/notification/notification.service';
use barrel or insert this service into it

2019-11-12 08:08 UTC, MatvienkoDO commented on frontend/src/app/core/header/header.component.ts
> +    private elRef:ElementRef
readonly

2019-11-12 08:08 UTC, MatvienkoDO commented on frontend/src/app/core/header/header.component.ts
> +    console.log(element);
console.log in prod - bad

2019-11-12 08:08 UTC, MatvienkoDO commented on frontend/src/app/core/header/header.component.ts
> +    const closeButton = this.elRef.nativeElement.querySelector('.mobile-menu__btn');
In such case it should be better to directly click input

2019-11-12 08:08 UTC, MatvienkoDO commented on frontend/src/app/core/header/header.component.ts
> +    const closeButton = this.elRef.nativeElement.querySelector('.mobile-menu__btn');
But, it is bad approach at all. We should not handle any logic in template and store data there

2019-11-12 08:08 UTC, MatvienkoDO commented on frontend/src/app/core/header/header.component.ts
> +    const closeButton = this.elRef.nativeElement.querySelector('.mobile-menu__btn');
I think tricks with labels, hidden inputs and ':checked' styles are acceptable only in case of strict prohibition of usage js

2019-11-12 12:11 UTC, linkouth commented on frontend/src/app/core/header/header.component.ts
> +    const closeButton = this.elRef.nativeElement.querySelector('.mobile-menu__btn');
It is the fastest and simplest way to realise.

2019-11-13 08:59 UTC, MatvienkoDO approved these changes

2019-11-13 08:59 UTC, MatvienkoDO commented on frontend/src/app/core/header/header.component.ts
>  import { NotificationService } from '../../shared/services/notification/notification.service';
Incorrect import. Use barrels

2019-11-13 08:59 UTC, MatvienkoDO commented on frontend/src/app/core/header/header.component.ts
> +    const closeButton = this.elRef.nativeElement.querySelector('.mobile-menu__btn');
referenced in issue

2019-11-13 09:04 UTC, merged

2019-11-13 09:13 UTC, MatvienkoDO commented on frontend/src/app/core/header/header.component.ts
>  import { NotificationService } from '../../shared/services/notification/notification.service';
merged before fix.
Will be made in https://github.com/MatvienkoDO/grid-dynamics-internship-project/pull/145